### ISSUE TITLE
Datenupload Node.VE

### ISSUE THREAD

**Issue by MarkusTiede** [open-prevo/openprevo#1]
Eine VE stellt Daten für die Node.VE bereit als Excel (Excel wird noch nachgeliefert)

Dies für folgende Fälle:

1. Neu angemeldete Versicherte, für die noch eine FZL erwartet wird
2. Ausgetretene Versicherte, für die noch keine FZL-Verwendung bekannt ist

Daten zur versicherten Person bei einem Austritt: 
 - AHV-Nummer 
 - Datum (Austrittsdatum)
 - UID der VE  
 - Referenz - Zur Identifikation der Person für die VE selbst

aus dem heutigen Meeting mit dem Datenschutzbeauftragten:
> „Referenz zur Identifikation der Person“ stark verschlüsseln so dass nur die Quelle des Datums entschlüsseln kann <oder> noch besser: direkt weglassen!

Daten zur versicherten Person bei einem Eintritt: 
 - AHV-Nummer 
 - Datum (Eintrittdatum)
 - UID der VE  
 - Referenz - Zur Identifikation der Person für die VE selbst = Überweisungstext für die andere VE
 - Name der VE
 - Zusatzname  (optional) der VE
 - Str / Postfach der VE
 - PLZ der VE
 - Ort der VE
 - IBAN der VE

Stand:
- [x] alle Daten aus Excel lesen
- [ ] Mit Node integrieren
- [ ] Frei wählbare Dateiname
- [ ] eventuell leeres Datei erstellen wenn keins vorhanden

Akzeptanzkriterien:
- Das Excel kann vom Node.VE verarbeitet werden
- Der Hub kann auf die Daten zugreifen

**Comment by Plattnea** [comment]
[Testdaten_Datenupload Node_VE_Struktur.xlsx](https://github.com/open-prevo/openprevo/files/2154950/Testdaten_Datenupload.Node_VE_Struktur.xlsx)
Struktur - Inhalt folgt

**Comment by lennartx** [comment]
Wenn wir auf der Tabelle Austritte und Eintritte trennen, können wir die Datenpflege vereinfachen - und auch falsche Inputdaten vermeiden (oder mindestens anzahl Fehler reduzieren).

Wie wäre es mit z.B. so eine Struktur (aus unserem aktuellen Test):
[retirement-fund-test-data_de.xlsx](https://github.com/open-prevo/openprevo/files/2162253/retirement-fund-test-data_de.xlsx)

**Comment by Plattnea** [comment]
aktuellste Struktur angepasst:
[Testdaten_Datenupload Node_VE_Struktur2.xlsx](https://github.com/open-prevo/openprevo/files/2163485/Testdaten_Datenupload.Node_VE_Struktur2.xlsx)
