### ISSUE TITLE
MVP Security-Tasks konkretisieren

### ISSUE THREAD

**Issue by MarkusTiede** [open-prevo/openprevo#109]
-Einsatz von Zertifikaten
-....

**Comment by MarkusTiede** [comment]
![attachment-1](https://user-images.githubusercontent.com/1764012/42760377-9bdee626-890a-11e8-9a58-6b438591627c.jpeg)

**Comment by MarkusTiede** [comment]
In der Runde zum heutigen Sprint 05 Start haben wir (@lennartx, @netopyr, @benoitpflieger, @jochenpilger, @hoehnb) uns auf folgende Tasks im MVP Scope geeinigt:

1. [ ] Aufnahme von Empfehlungen hinsichtlich Transport-Layer Security in die arc42 Doku
1. Authentifizierung und Autorisierung sind nicht Teil des MVP
1. [ ] Payloads werden asymmetrisch verschlüsselt
1. [ ] AHV-Nummern werden gehashed verarbeitet
1. [ ] Wir recherchieren (TB 4h) Wege zur Hub-neutralen Verteilung von Schlüsselpaaren
1. [ ] Wir implementieren im Hub einen Sanity-Check bzgl. der UID Verwendung durch die Nodes

**Comment by netopyr** [comment]
Ergebnis der Recherche:

Um unverfälschbare und verschlüsselte Kommunikation zwischen zwei Nodes sicherstellen zu können, muss garantiert werden, dass der öffentliche Schlüssel tatsächlich von dem anderen Node kommt. Grundsätzlich gibt es drei Lösungsansätze, um die öffentlichen Schlüssel zu verteilen, die in unserem Fall praktikabel erscheinen.

1. Neben dem Hub wird noch ein zentraler Key Server für die öffentlichen Schlüssel aufgesetzt. Immer wenn benötigt, holen sich die Nodes die benötigten öffentlichen Schlüssel vor dort. Wesentlich bei diesem Verfahren ist, dass nur authorisierte Personen die Schlüssel ihrer VE ändern dürfen. Zusätzlich sollte eine Notifizierung versendet werden, wenn die Daten einer VE geändert werden. 
Es stellt sich natürlich die berechtigte Frage, warum die VEs dem Key Server vertrauen sollen, wenn sie dem Hub nicht trauen. Manipulationen sind hier aber viel eher zu entdecken, da die Daten des Key Servers ja jederzeit öffentlich einsehbar und damit auch überprüfbar sind.
Technisch würde ein LDAP vermutlich schon ausreichen, es gibt aber auch einige spezialisierte Key Server, insbesondere im PGP-Umfeld.

1. Die Verwaltung und Verteilung der öffentlichen Schlüssel wird von einer dritten, unabhängigen Partei übernommen. Es gibt mittlerweile Dienstleister, die PKI als Service anbieten. Bei dieser Lösung ist die Schlüsselverteilung vollständig vom Hub getrennt, allerdings muss dafür dem PKI-Dienstleister vertraut werden.

1. Ein völlig anderer Ansatz ist ein "Web of Trust". Wenn ein Teilnehmer in einem Web of Trust sicher ist, dass ein Public Key einem anderen Teilnehmer gehört, kann er ihn signieren. Je mehr Signaturen der Public Key einer mir unbekannten Person aufweist, desto eher kann ich ihr vertrauen. Problematisch ist bei diesem Ansatz allerdings immer die Frage, wie ein neuer Teilnehmer seine ersten Signaturen bekommt. 
Dieser Ansatz ist vermutlich der für unsere Zwecke am wenigsten praktikable und sollte meiner Meinung daher nur gewählt werden, wenn sich die VEs vorrausichtlich nicht auf eine zentrale Instanz einigen können, der alle vertrauen.
