### ISSUE TITLE
Anbindung an PAKT

### ISSUE THREAD

**Issue by Plattnea** [open-prevo/openprevo#11]
1. Ein-Austritts-GeschäftsVorfälle in PAKT -> Daten auf Tabelle schreiben
Es sollen bei jedem Dienstein- oder Dienstaustritt, der in PAKT verarbeitet wird (Gevo abgeschlossen) Attribute in eine Tabelle geschrieben werden. 
-	Egal ob er einzeln, seriell, über WebServices oder WebPAKT gemeldet resp. verarbeitet wurde. 
-	Ausgenommen sind die Transfer-Gevos
-	Nur Gevos mit der Gevo Verwendung = Normal

Ziel ist, dass diese Daten später der Plattform zur Verfügung gestellt werden können. Datumswerte sollen später dazu dienen, alte Einträge zu identifizieren und aus der Tabelle entfernen zu können.  

 a.	Dienstaustritt (DA)
Nur speichern wenn
- eine FZL auszuzahlen ist
- UND die neue VE NICHT bekannt ist (in diesen Fällen erstellt PAKT eine Inkonsistenz und idR eine Terminkette)

Abgespeichert werden:
Art       Austritt
- Name
- Vorname
- Geschlecht
- Geburtsdatum
- Sozialversicherungsnummer (optionale Angabe)
- Datum des Austritts
- Datum Gevoabschluss
- Identifikation für VE = IdGeschäft Vtr und IdGeschäft Police – beide in der Langversion

 b.	Diensteintritt (DE)
Nur wenn Untersparte gleich
 - 3  Voll-/Risikoversicherung
 - 4  Sparen Invest 
d.h. NICHT wenn Untersparte =
 - 1  FZP
 - 2  Externes Sparen
 - 5  SPAB
Art       Eintritt
- Name
- Vorname
- Geschlecht
- Geburtsdatum
- Sozialversicherungsnummer (optionale Angabe)
- Datum des Eintritts (WD)
- Datum Gevoabschluss
- Identifikation für VE = IdGeschäft Vtr und IdGeschäft Police – beide in der Langversion

2.	Plattform holt Daten ab
Die Plattform holt bei registrierten Vorsorgeeinrichtungen (VE) (d.h. Pensionskasse, Gemeinschaftsstiftung, Sammelstiftung, Lebensversicherer, aber auch Freizügigkeitseinrichtungen, etc.) 

Daten ab, die diese an dedizierter Stelle zur Verfügung stellen. 

Zugriff auf die Daten haben nur die entsprechende VE selbst (upload) und die Plattform (read).

Informationen zum Versicherten
•	Art (Eintritt / Austritt)
•	Name
•	Vorname
•	Geschlecht
•	Geburtsdatum
•	Sozialversicherungsnummer (optionale Angabe)
•	Identifikation Person für VE

3.	Matching
Bereits formuliert in Github

4.	Matching mitteilen
Bereits formuliert in Github

5.	Matching-Info in PAKT-Webservice abfüllen
Anhand der von der Plattform erhaltenen Daten den Webservice „submitFZLVerwendung“ ausführen mit folgenden Attributen:

idPartner         >wird mit der Id der VE gefüllt
cdZweck         = 1 Vorsorgeeinrichtung extern
idGeschaeft    = leer lassen
slPartnerChecked >ja 
CdWhg            >CHF
CdGrdAusz     = leer lassen
dtUnterVoll      >Datum der Verarbeitung
txtUebw           >von der Plattform erhaltenen Überweisungstext
cdAntFzl          = 3 gesamt

6.	PAKT – Parametrisierung FZL auszahlen
Für den anzuwendenden Mandaten soll die Parametrisierung so vorgenommen werden, dass vom Webservice „submitFZLVerwendung“ aus die Auszahlung der FZL automatisch erfolgt und dunkel abgeschlossen wird.

Falls möglich: Die Parametrisierung so einstellen, dass in 50% der Fälle eine Stichprobe erfolgt und damit die Verarbeitung auf hell ändert.

**Comment by jochenpilger** [comment]
Diese Story muss aufgeteilt werden. (!)
