### ISSUE TITLE
Naming 

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#12]
-AHV IDs
-- in english ? 
-- abtract name?

... other terms
-> update glossar
-> ask other players

**Comment by lennartx** [comment]
The Swiss authorities has several multi language publications relating to the second pillar, e.g. [https://www.bsv.admin.ch/bsv/en/home/informations-for/auswanderer/swiss-social-insurance-system--sojourn-in-switzerland-and-depart.html](Swiss social insurance system: Sojourn in Switzerland and departure)

**Comment by MarkusTiede** [comment]
Thanks! - sources used:

[italienisch_assicurazionisocialisoggiornoinsvizzeraepartenzainfo.pdf](https://github.com/open-prevo/openprevo/files/2136527/italienisch_assicurazionisocialisoggiornoinsvizzeraepartenzainfo.pdf)
[franzoesisch_assurancessocialessejourensuisseetdepartinformation.pdf](https://github.com/open-prevo/openprevo/files/2136528/franzoesisch_assurancessocialessejourensuisseetdepartinformation.pdf)
[englisch_swiss_socialinsurancesystemsojourninswitzerlandanddepar.pdf](https://github.com/open-prevo/openprevo/files/2136529/englisch_swiss_socialinsurancesystemsojourninswitzerlandanddepar.pdf)
[deutsch_sozialversicherungenaufenthaltinderschweizundausreiseinf.pdf](https://github.com/open-prevo/openprevo/files/2136530/deutsch_sozialversicherungenaufenthaltinderschweizundausreiseinf.pdf)
