### ISSUE TITLE
Rename 'data-model' modules

### ISSUE THREAD

**Issue by lennartx** [open-prevo/openprevo#125]
The current naming is confusing, and does not really convey the intended usage: `data-model` is shared between a node and its adapter, and `encrypted-data-model` is shared between the hub and its nodes.

Some name suggestions:
- hub-node-api
- hub-node-model
- hub-api
- node-adapter-api
- node-adapter-model
- node-api
- adapter-api

**Comment by MarkusTiede** [comment]
For "data-model"I like to modul name "node-api"; however I'd expect the package names to not explicitly include the ".api." within their namespace.

The same applies for the hub: encrypted-data-model -> "hub-api"
