### ISSUE TITLE
Data processing compliance

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#13]
1. Es ist Vorsorgeeinrichtungen erlaubt, die frühere resp. die neue eines Versicherten in Erfahrung zu bringen, weil es ihre gesetzliche Pflicht ist (frühere VE) oder sie das gemäss Gesetz explizit dürfen (neue VE). 
- Die frühere VE hat die Pflicht, die FZL an die neue VE zu überweisen, wenn Versicherte eine neue haben. (FZG Art.3 Abs1)
- Der Versicherte hat keine Wahl. Nur wenn er keine neue VE hat, steht ihm eine zu. (FZG Art.4 Abs1)
- Die neue VE kann die FZL bei der früheren einfordern. (FZG Art.11 Abs2)

2. Bei Eintritt in eine VE kann die Austrittsleistung auch bei Freizügigkeitseinrichtungen eingefordert werden.
- Treten Versicherte in eine neue VE ein, so müssen die Freizügigkeitseinrichtungen das Vorsorgekapital der neuen VE überweisen. (FZG Art.6 Abs2bis)

3. Auf der Plattform dürfen keine Versichertendaten in Klartext verarbeitet werden. Solche Daten sind so zu verschlüsseln, dass nur Berechtigte sie lesen können.
- Grundsätzlich gilt eine Verschwiegenheitspflicht. Ausnahmen sind abschliessend im Gesetz geregelt.
- Es ist nicht zweifelsfrei, ob der Plattform Versichertendaten bekannt gegeben werden dürfen. 
- BVG Art.86a lässt es nur zu an "mit der Durchführung sowie der Kontrolle oder der Beaufsichtigung der Durchführung dieses Gesetzes betrauten Organe, wenn sie für die Erfüllung der ihnen nach diesem Gesetz übertragenen Aufgaben erforderlich sind"

*Akzeptanzkriterien*
- Diese Rahmenbedingungen sind öffentlich dokumentiert.
- Review bei Datenschutzbeauftragten

**Comment by mikaelkalt** [comment]
👍
