### ISSUE TITLE
Housekeeping: move "CapitalTransferInformation" related classes to the "Node/Adapter" api module

### ISSUE THREAD

**Issue by lennartx** [open-prevo/openprevo#151]
They're never used by the Hub, and should not appear in this api module

**Comment by mikaelkalt** [comment]
They are part of our Adapter API? At least our EmploymentCommencement class contains a `CapitalTransferInformation` which would then result in a dependency from the adapter to the node, which we wanted to prevent.

**Comment by netopyr** [comment]
+1
It needs to be moved to the data-model, because it is shared between adapter and node.

**Comment by mikaelkalt** [comment]
You're right, since we have now the encrypted capital transfer information we can move it back to data-model (before it was used by the hub that was the reason we were not able to move it). 

Anyways I'd be happy if you wait until #2 is merged.
