### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#18]
Offene Punkte
- [ ] Datensätze einsammeln
- [ ] Datensätze für alle zur Verfügung stellen,

**Comment by Plattnea** [comment]
Hier drin gibt es Testdaten von 2 "Excel-VE" und für PAKT
[Testdaten MVP.zip](https://github.com/open-prevo/openprevo/files/2170670/Testdaten.MVP.zip)
