### ISSUE TITLE
Letztes Review vorbereiten. (30.7.)

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#180]
-Drehbuch
-Schaubild Verschlüsselung

---

*Intro mit Context*
- Endvisionsgrafik von Adrian (mit allem) => Adrian
- MVP-Grafik von Adrian (nur MVP) => Adrian 

*Business Context*
- Grafiken aus Arc42 (Business Context und MVP Business Context)

*Demo auf Prevo PC :1st_place_medal:*
- alle vier Richtungen werden gleichzeitig gezeigt
-Teilnehmer: Zurich, Helvetia und Basler
-Intro mit Hilfe des Wordfiles
-Erklärung des kompletten Durchlaufs
-Pakt, Hub und Nodes starten
-Validierung passiert, Ergebnis ist da.
-Ergebnis im Excel und im PAKT zeigen

_Die drei Ziele des MVP_
- alle vier Richtungen
- leichte Demofähigkeit
- einfache produktivsetzungsfähigkeit

*OpenSource Gedanke*
GitHub, Travis, 
- wo ist die Demo.zip zu finden, 
- wo ist die Doku zu finden
- Wo sind die Slides zu finden

Was ist alles verschlüsselt und wie?
- alles siehe https://open-prevo.github.io/openprevo/#_security_and_data_protection
- AHV Nummer (Hash)
- Zahlungsinformation (Hash)
- Zertifikate mit Private und Public Keys der Nodes

Weiteres Technische Details Verschlüsselung aus dem aktuellen Sprint
:+1: 

*Ausblick*
- MVP ist zu Ende
- Product befindet sich auf GitHub
- Steering Comitee tagt am 14.8.

**Comment by MarkusTiede** [comment]
Review hat stattgefunden.
