### ISSUE TITLE
Reduce data to OASI only

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#19]
For the MVP, we reduce the matching to the OASI number. That means: The only key for a match is the OASI number.

Reason:
If, at a later stage, people will also get mached while a RF does not have an OASI number, it should be checked whether the platform could offer:

For each person without OASI number, the OASI number is requested via an existing service at the Central Compensation Office (CCO). If there is a single hit, we continue with this OASI number. If there is no hit or more than one, the RF will get informed about.

**Comment by Plattnea** [comment]
Please review

**Comment by lennartx** [comment]
:+1:

**Comment by mikaelkalt** [comment]
👍
