### ISSUE TITLE
Matching Hub

### ISSUE THREAD

**Issue by Plattnea** [open-prevo/openprevo#3]
Aktion auf dem Hub

Anhand der von den Node.VE gelesenen Daten ermittelt der Hub passende Eintritte zu passenden Austritten = Match

Im Rahmen des MVP gilt als ein Match : 

• wenn die AHV Nummer identisch ist

Kein Treffer ist, wenn
• Eintrittsdatum ist vor dem Austrittsdatum 
UND
• UID [Eintritt] ist gleich UID [Austritt]

ODER
Kein Treffer ist, wenn 
• ein Treffer bereits notifiziert wurde (siehe #35 Treffer merken)

Akzeptanzkriterien
- Nur die definierten Fälle werden als Treffer gemeldet.

**Comment by lennartx** [comment]
Wir erleben anscheinend immer wieder, dass die Kombination Geschlecht + Geburtsdatum + Name + Vorname für einen Partnermatch nicht ganz ausreichend ist, und es ist nötig, auch die Domiziladresse zu vergleichen

**Comment by mikaelkalt** [comment]
Würde es Sinn machen, das Austritt- und Eintrittsdatum ebenfalls zu prüfen? Zumindest, dass Austritt vor Eintritt sein muss - jedoch darf die Differenz nicht grösser als z.B. ein halbes Jahr sein (weil es sonst auf ein Freizügigkeitskonto überwiesen werden müsste)?
