### ISSUE TITLE
Aus AHV-Nr einen Hash erstellen

### ISSUE THREAD

**Issue by Plattnea** [open-prevo/openprevo#30]
Aus der AHV-Nummer wird ein Hash erstellt, aus dem die Original-AHV-Nummer nicht ermittelbar ist. 
Es darf wenn möglich keine Hash-Kollisionen geben (gleicher Hash bei unterschiedlicher AHV-Nummer).

Alle Nodes aller VE müssen bei gleicher AHV-Nummer den gleichen Hash erhalten damit der HUB gleiche Hashes erkennen kann.

Die Node.VE muss später - wenn ein Treffer gemeldet wird - wieder auf die AHV-Nummer zurückschliessen können. 

Akzeptanzkriterium:
@marcellobellini muss mit dem gewählten Verfahren einverstanden sein.

**Comment by marcellobellini** [comment]
Ich empfehle basierend auf BSI TR-02102-1 (https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102.pdf;jsessionid=FDCFE98CBC7E634FD7291729504BB8A9.2_cid351?__blob=publicationFile&v=8)

den Einsatz von SHA-2 oder SHA-3 Hash-Funktionen, z.B. SHA-512 oder SHA3-512.

Welche Daten stehen zur Verfügung die für die Berechnung des Hash-Wertes genutzt werden können?
- Name
- Vorname
- AHV-Nummer

Aus den Daten könnte der folgende Hash generiert werden SHA512(Name+Vorname+AHV)-
Ist das ein möglicher Ansatz?

**Comment by lennartx** [comment]
Aktuell steht uns eigentlich nur das AHV-Nummer zur Verfügung. Wäre dies zu knapp?

**Comment by marcellobellini** [comment]
Eine AHV Nummer ist eigentlich anonym enthält selber keine personenbezogene Daten. 
Wir müssen uns das Bedrohungsmodell nochmal anschauen, ggf. brauchen wir den Hash gar nicht

**Comment by MarkusTiede** [comment]
Die ["Verordnung des EDI" beschreibt das Handling der OASI](https://open-prevo.github.io/openprevo/#_verordnung_des_edi_background_usage_of_oasi_numbers) relativ genau.
