### ISSUE TITLE
Datenupload Hub

### ISSUE THREAD

**Issue by Plattnea** [open-prevo/openprevo#32]
Der Hub holt sich die Daten bei der Node.VE, die für das Matching benötigt werden

Daten zur versicherten Person: 
 - AHV-Nummer - Hash 
 - Datum (Eintrittsdatum resp Austrittsdatum)
 - Art: Austritt / Eintritt 
 - UID der VE  

Akzeptanzkriterien:
- Der Hub hat die Daten und kann beim Matching auf sie zurückgreifen

**Comment by mikaelkalt** [comment]
@lennartx I assume this is done, since you've added the date to the class `InsurantInformation`
