### ISSUE TITLE
Erstellung von den DA und DE aus PAKT

### ISSUE THREAD

**Issue by benoitpflieger** [open-prevo/openprevo#39]
**Diese Issue ist eine Aufteilungspacket der Issue #11:**

> 1. Ein-Austritts-GeschäftsVorfälle in PAKT -> Daten auf Tabelle schreiben
> Es sollen bei jedem Dienstein- oder Dienstaustritt, der in PAKT verarbeitet wird (Gevo abgeschlossen) Attribute in eine Tabelle geschrieben werden. 
> -	Egal ob er einzeln, seriell, über WebServices oder WebPAKT gemeldet resp. verarbeitet wurde. 
> -	Ausgenommen sind die Transfer-Gevos
> -	Nur Gevos mit der Gevo Verwendung = Normal
> 
> Ziel ist, dass diese Daten später der Plattform zur Verfügung gestellt werden können. Datumswerte sollen später dazu dienen, alte Einträge zu identifizieren und aus der Tabelle entfernen zu können.  
> 
>  a.	Dienstaustritt (DA)
> Nur speichern wenn
> - eine FZL auszuzahlen ist
> - UND die neue VE NICHT bekannt ist (in diesen Fällen erstellt PAKT eine Inkonsistenz und idR eine Terminkette)
> 
> Abgespeichert werden:
> Art       Austritt
> - Name
> - Vorname
> - Geschlecht
> - Geburtsdatum
> - Sozialversicherungsnummer (optionale Angabe)
> - Datum des Austritts
> - Datum Gevoabschluss
> - Identifikation für VE = IdGeschäft Vtr und IdGeschäft Police – beide in der Langversion
> 
>  b.	Diensteintritt (DE)
> Nur wenn Untersparte gleich
>  - 3  Voll-/Risikoversicherung
>  - 4  Sparen Invest 
> d.h. NICHT wenn Untersparte =
>  - 1  FZP
>  - 2  Externes Sparen
>  - 5  SPAB
> Art       Eintritt
> - Name
> - Vorname
> - Geschlecht
> - Geburtsdatum
> - Sozialversicherungsnummer (optionale Angabe)
> - Datum des Eintritts (WD)
> - Datum Gevoabschluss
> - Identifikation für VE = IdGeschäft Vtr und IdGeschäft Police – beide in der Langversion

**Comment by Plattnea** [comment]
[Testdaten_Datenupload Stiftungen Baloise.xlsx](https://github.com/open-prevo/openprevo/files/2158538/Testdaten_Datenupload.Stiftungen.Baloise.xlsx)
