### ISSUE TITLE
Unify naming on node / hub

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#41]
In particular: consider using terms like "entering" or "leaving" a pension fund instead of starting or quitting a job, as we're really only interested in employees who are insured in pension funds (e.g. not those below the income threshold)

If we do decide to keep "changing employer" as our core concept, the current glossary terms are:
- Employer Change
- Commencement of Employment
- Termination of Employment

Candidates to change:
- [x] JobEvent -> EmployerChange
- [x] JobEnd -> EmploymentTermination
- [x] JobStart -> EmploymentCommencement
- [x] VE -> RF
- [x] HUB -> Hub (avoid TLA confusion)
- [x] TerminationMatchNotification -> MatchForCommencement (moved from #80)
- [x] CommencementMatchNotification -> MatchForTermination (moved from #80)

Type of renamings
- [x] REST Endpoints
- [x] classes
- [x] methods
- [x] *.adoc references
- [x] picture inclusions

Auch im Glossar aktualisieren

**Comment by lennartx** [comment]
Suggest that we also rename the "model" modules to make them more expressive, e.g.:
- [ ] encrypted-data-model -> hub-node-data-model 
- [ ] data-model -> node-adapter-data-model
