### ISSUE TITLE
Apply for DINAcon Awards 2018

### ISSUE THREAD

**Issue by MarkusTiede** [open-prevo/openprevo#52]
## Summary / Zusammenfassung

Gain visibility by applying for the [DINAcon Awards 2018](https://dinacon.ch/dinacon-awards/project-submission/)

**Comment by MarkusTiede** [comment]
## OpenPrevo

An open prévoyance professionnelle platform supporting the second pillar of the Swiss retirement provision.

The vision of this open, swiss-wide usable platform (OpenPrevo Hub) has just been started by working on an MVP (Minimum Viable Product) for six weeks. Within this time we've been focusing on automating the process of finding new retirement funds when changing jobs.

Currently we're in the stage of spreading the word about the project and getting to know other interested parties.

All sources and information are completely publicly available here: https://open-prevo.github.io

### Contact Name and eMail
Markus Tiede

### Company Name
Basler Versicherungen AG and Prevo-System AG

**Comment by mikaelkalt** [comment]
if that's enough, I'd say 👍

**Comment by jochenpilger** [comment]
sounds great!

**Comment by MarkusTiede** [comment]
![dina](https://user-images.githubusercontent.com/1764012/42725466-1666b47e-8784-11e8-9b78-31832e6d932e.png)
