### ISSUE TITLE
Notify mit Excel

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#63]
best case: kommt ein Excel in der gleichen Struktur zurück
- [ ] Diskutieren
- [ ] Umsetzen
- mindestens jedoch ein File mit Inhalt

**Comment by mikaelkalt** [comment]
@Plattnea Ist das nicht ein Duplikat von https://github.com/open-prevo/openprevo/issues/4? Ich denke, dann können wir das hier schliessen und das andere in den Sprint ziehen?

**Comment by MarkusTiede** [comment]
See #4
