### ISSUE TITLE
Deployments Nodes

### ISSUE THREAD

**Issue by jochenpilger** [open-prevo/openprevo#66]
Create a package like e.g. a ZIP file that contains different folders with different nodes. 

- hub
  - needs a configuration for all nodes
  - startup script to start the node
  - maybe later a script to clean the database
- node-baloise-excel
  - startup script to start the node
- node-baloise-pakt
  - startup script to start the node
- node-helvetia
  - startup script to start the node
- node-zurich
  -startup script to start the node

definitions see #64 

sub tasks
- [x] demo module with build logic (output: all demo files)
- [x] assemble zip file for demo
- [x] adjust node + hub ports if needed
- [x] add all node ports to hub
- [x] externalize hub config (optional)

**Comment by lennartx** [comment]
Changes in branch feature/66_deployment_nodes
