### ISSUE TITLE
"Termination" / "Commencement" used inconsistently in MatchNotificationController (and callers)

### ISSUE THREAD

**Issue by lennartx** [open-prevo/openprevo#80]
The rest endpoint 
`"/commencement-match-notification"` accepts a `TerminationMatchNotification`, and vice versa for the`"/termination-match-notification"`.

Callers mirror this cognitive overload, we should probably fix it. But please wait for #60 to prevent a too painful merge.

**Comment by mikaelkalt** [comment]
Well you're right this is kind of a brainfu*** 😄 but it's also very hard to properly name it. I'm very open for a good suggestion 👍

**Comment by lennartx** [comment]
Naming aside, this is a bug: the method "commencement-match-notification" takes a parameter of type "TerminationMatchNotification" - and "termination-match-notification" uses a "CommencementMatchNotification". 

The names have been switched.

**Comment by mikaelkalt** [comment]
@lennartx this is done by #111, I'd say?
